version: '3.8'

services:
  mysql:
    image: mysql:8.0

    container_name: umc_db

    environment:
      # .env 파일에서 MYSQL_ROOT_PASSWORD 변수를 참조
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

      # .env 파일에서 MYSQL_DATABASE 변수를 참조
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    restart: always

volumes:
  mysql_data: