package com.example.umc9th.domain.member.enums;

public enum Address {
    GANGNAM, GANGDONG, GANGBUK, GANGSEO, GWANAK, GWANGJIN, GURO, GEUMCHEON, NOWON, DOBONG, DONGDAEMUN, DONGJAK, MAPO, SEODAEMUN, SEOCHO, SEONGDONG, SEONGBUK, SONGPA, YANGCHEON, YEONGDEUNGPO, YONGSAN, EUNPYEONG, JONGNO, JUNG, JUNGNANG
}
